### ISSUE TITLE
Any plans for supporting React Native v0.6?

### ISSUE THREAD

**Issue by dinotrnka** [ProjectSeptemberInc/gl-react-native#204]
Hi,

Are there any plans for supporting RN v0.6? I am migrating a project, so I'd appreciate knowing whether to wait for the update or to move on to another library. Thanks!

**Comment by dinotrnka** [comment]
Hi,

Can anyone please answer? A simple yes/no is fine.

Thanks!

**Comment by gre** [comment]
I guess you meant 0.60?

This project is not well maintained at the moment but I accept PR to fix this state.
I'll bump a new version with recent PR work to see if it helps. Please reach back to me if there are still issues with it. Thanks

**Comment by dinotrnka** [comment]
> I guess you meant 0.60?
> 
> This project is not well maintained at the moment but I accept PR to fix this state.
> I'll bump a new version with recent PR work to see if it helps. Please reach back to me if there are still issues with it. Thanks

Thank you!
I will check the new version and will let you know if it works.

**Comment by dinotrnka** [comment]
Hi, 

I just tried to update `gl-react-native`, and I installed the v2.60.0. However, it's not working with the latest version of `gl-react@3.15.0`.

In other words, if I try to run the app with this setup:
```
├── UNMET PEER DEPENDENCY gl-react@3.15.0 
├── gl-react-native@2.60.0 
└── react-native@0.60.4 
```

I get this exact error: https://github.com/gre/gl-react/issues/219

So I guess the correct thing to do is follow this advice:
`gl-react-native@2.60.0 requires a peer of gl-react@^2.2.4 but none is installed. You must install peer dependencies yourself.`

The problem is when I install `gl-react@^2.2.4`, it requires another peer:
`npm WARN gl-react@2.2.4 requires a peer of react@^0.14.5 || ^15.0.0 but none is installed. You must install peer dependencies yourself.`

And if I downgrade react to `@0.14.5` or `@15.0.0` it breaks a lot of stuff, because it's too low.

Do you have any advice? I might be close to the solution but can't seem to figure it out.
Thanks a lot, much appreciated!

**Comment by gre** [comment]
yes it needs the v2 of gl-react.  gl-react-native-v2 is incompatible with gl-react @ 3
the peer dep is just a warning so it should still be fine to ignore. But this will have to be fixed in https://github.com/gre/gl-react-v2

**Comment by dinotrnka** [comment]
Thank you very much for the response!

The problem is, when I run the app with this setup, I get the error message `Module gl-react/src/isAnimated does not exist in the Haste module map`, similar to this issue: https://github.com/gre/gl-react/issues/219

I tried to remove node_modules folder and install everything from the beginning, but it just leads to the same error.

**Comment by dinotrnka** [comment]
I'm bumping this issue so it doesn't get stale. Did anyone else try to run gl-react-native on the latest React Native version?

**Comment by dinotrnka** [comment]
Can anyone help?

**Comment by superandrew213** [comment]
It works fine for me on RN0.60.

Try `npm start -- --reset-cache`.

**Comment by viewpnt1** [comment]
I'm having trouble going through android build process during upgrade to react-native 0.60.5.

``` 
 What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
 com.android.build.api.transform.TransformException: Error while generating the main dex list:
  Error while merging dex archives: 
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: com.projectseptember.RNGL.BuildConfig
```

Anyone encountered this yet?

**Comment by viewpnt1** [comment]
After a while I found this in gradle log:
```
Configure project :gl-react-native WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'. It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
```
So I figured that somehow the module was already included alongside old RNGL module. I ended up removing the RNGL from gradle.build and gradle.settings (basically manual unlink) and build is ok now. 
The fact is, as of 0.60 RN is automatically linking libraries, but somehow only this library caused a problem. My bet is that its because the names do not overlap and they probably do overlap in all other libraries (all use node_modules folder name except RNGL).

**Comment by dinotrnka** [comment]
> It works fine for me on RN0.60.
> 
> Try `npm start -- --reset-cache`.

I managed to fix that problem with the `--reset-cache`, but now react-native-webgl fails. 

`In file included from /Users/dinotrnka/Documents/git/woc-mobile/node_modules/react-native-webgl/ios/RNWebGLTextureLoader.m:1:
/Users/dinotrnka/Documents/git/woc-mobile/node_modules/react-native-webgl/ios/RNWebGLTextureLoader.h:1:9: fatal error: 'React/RCTBridge.h' file not found
#import <React/RCTBridge.h>`

I'm just running in loops here, I'm trying to make the crop functionality work but each time something new fails. =

**Comment by dinotrnka** [comment]
> It works fine for me on RN0.60.
> 
> Try `npm start -- --reset-cache`.

I managed to fix that problem with the `--reset-cache`, but now react-native-webgl fails. 

`In file included from /Users/dinotrnka/Documents/git/xxxxxxxxxxx/node_modules/react-native-webgl/ios/RNWebGLTextureLoader.m:1:
/Users/dinotrnka/Documents/git/xxxxxxxxxxx/node_modules/react-native-webgl/ios/RNWebGLTextureLoader.h:1:9: fatal error: 'React/RCTBridge.h' file not found
#import <React/RCTBridge.h>`

I'm just running in loops here, I'm trying to make the crop functionality work but each time something new fails.

**Comment by dinotrnka** [comment]
OK, I finally got it. Here's the combination that works on React Native v0.60.4:

"gl-react": "^2.3.1"
"gl-react-native": "^2.60.0"
